In [2]:
# numpy
# 수치 계산용 라이브러리
# 고도의 수학 알고리즘과 배열을 조작하기 위한 메서드 준비
# 딥러닝 훨씬 호율적 구현

In [3]:
# matplotlib
# 그래프를 그려주는 라이브러리
# 실험결과를 시각화하거나, 딥러닝 실행 과정의 중간 데이터를 시각적으로 확인

In [4]:
# 자료형
# type()
type(10)

int

In [5]:
# numpy 
# 외부 라이브러리
import numpy as np

In [6]:
# numpy array
x = np.array([1.0, 2.0, 3.0])
print(x)
print(type(x))

[1. 2. 3.]
<class 'numpy.ndarray'>


In [7]:
# element-wise : 원소별
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
print(x + y)
print(x - y)
print(x * y)
print(x / y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [8]:
# broadcast
x/2.0

array([0.5, 1. , 1.5])

In [9]:
# 2차원 배열
A = np.array([[1,2], [3,4]])
print(A)

[[1 2]
 [3 4]]


In [10]:
print(A.shape)
print(A.dtype)

(2, 2)
int64


In [11]:
B = np.array([[3,0], [0,6]])
A + B

array([[ 4,  2],
       [ 3, 10]])

In [12]:
A * B

array([[ 3,  0],
       [ 0, 24]])

In [13]:
A * 10

array([[10, 20],
       [30, 40]])

In [14]:
# 1 차원 : 벡터
# 2 차원 : 행렬
# 텐서 : 벡터와 행렬을 일반화 한 것

In [15]:
X =  np.array([[51,55], [14,19], [0,4]])
print(X)

[[51 55]
 [14 19]
 [ 0  4]]


In [16]:
X = X.flatten()  # x를 1차원 배열로 변환 (평탄화)
print(X)

[51 55 14 19  0  4]


In [17]:
X[np.array([0,2,4])]   # 특정 인덱스 열거

array([51, 14,  0])

In [18]:
X > 15

array([ True,  True, False,  True, False, False])

In [19]:
X[X>15]

array([51, 55, 19])

In [21]:
# 파이썬 같은 동적언어는 c+/c++ 같은 정적언어(컴파일 언어)보다 처리 속도가 늦다고 함
# 실제로 무거운 작업을 할 때는 c+/c++ 쓰는 편이 좋음
# 파이썬은 c+/c++ 쓰인 프로그램을 호출해주는 이른바 중개자 같은 역할
# numpy도 주된 처리는 c/c++ 구현